### ISSUE TITLE
Breaking interface changes in 0.2.2 of openapi_utils

### ISSUE THREAD

**Issue by 197g** [JordiPolo/oas_proxy#4]
This just informative, but the release 0.2.2 was a breaking on. Let's explain, with the example of `SpecExt`. The goal here is to raise some awareness regarding version compatibility of public dependencies.

In  [`0.2.1`](https://docs.rs/openapi_utils/0.2.1/openapi_utils/trait.SpecExt.html#tymethod.deref_all) it was implemented for `OpenAPI` from `openapiv3 = 0.3`. However in [`0.2.2`](https://docs.rs/openapi_utils/0.2.2/openapi_utils/trait.SpecExt.html#tymethod.deref_all) it is _instead_ implemented for `OpenAPI` from `openapiv3 = 0.5`. In other words, this release _removed_ an impl since the crate versions `0.3` and `0.5` are not compatible with each other. It also added another one.

This causes downstream issues in, for example, <https://github.com/matusf/openapi-fuzzer>. All downstream crates should update their own dependencies on `openapiv3` to fix this issue.

If possible, this issue can be avoided if any incompatible version bump of public dependencies are only performed on an incompatible version bump of the library in question. Alternatively, you can add _both_ dependencies with renames and keep the old impl. (If this is behind optional dependencies with defaulting to the previous version then it's still technically not perfect but downstream crates should continue to compile).

**Comment by JordiPolo** [comment]
Good point. I am terribly sorry. 
I have just releases 0.3.0 which again updates to latest openapiv3 dependency which have incompatible changes.

**Comment by 197g** [comment]
Thank you! For handling the release process well now and for your contributions with this crate. I suppose now that the dependency reached `1.0` you'll have much fewer troubles—as `1.0` is treated as compatible to `1.1`, allowing you to do such a bump.

**Comment by JordiPolo** [comment]
BTW, I've checked your openapi-fuzzer project and I think we have had a similar idea  https://github.com/JordiPolo/minos

In my case, in addition to random fuzzing I allow passing parameters. Mainly because the APIs I work on usually work with UUIDs, if you do not know them that's a lot of 404 and little more that you'll get back. 

On the other hand, I do not have `resend`. Maybe we can find some way to collaborate. 

Internally it has this crate https://github.com/JordiPolo/minos/tree/master/crates/daedalus I have not documented or anything as it was used internally only. This crate implements the "fuzzing" I call it autogeneration of  scenarios.

When you call it you get a Vec<Scenario> which is this https://github.com/JordiPolo/minos/blob/master/crates/daedalus/src/scenario.rs#L10-L15

It has the request to be made and the response expected. The binary then does the requests, compares the responses, etc. If you are interested I can publish daedalus as its own crate with docs, etc.

**Comment by 197g** [comment]
It's not my project in that I was a user trying to compile it for some internal tool at an inopportune time. However, this does sound very interesting and you could/should possible ask for collaboration with them directly. Just some input on the UUID style, since I'm also using this, the OpenAPI specification has concepts of [Links](https://swagger.io/specification/#linkObject) and [Runtime Expressions](https://swagger.io/specification/#runtimeExpression)  which can be used to point to related resources based on a server response. It sounds like this information could help the fuzzer find probably additional paths to try.
